### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapipes#426]
I would like to summarize some other issued and make a collection of what's still missing in the documentation. I found:

- [ ] set_user_pf_options: some better documentation (cf. #425 ), please improve on https://pandapipes.readthedocs.io/en/latest/pipeflow/options.html#user-options
- [ ] press_control component (cf. #414 )
- [ ] flow_control component
- [ ] compressor component
- [ ] update hard-coded parts for the new components (e.g. for plotting, cf. https://pandapipes.readthedocs.io/en/latest/plotting/simple_plot.html)
- [ ] possibly some parts of time series (cf. #224 )
- [ ] toolbox functions (some were added, some might need updates)

If you find any further parts that are missing or need to be updated, please extend the list.
